server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wechat_food_order?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

#sa-token:
#  token-name: satoken    # token名称
#  timeout: -1            # 有效期永久（单位：秒）
#  active-timeout: -1   # 无操作续期（-1不续期）
#  is-concurrent: false   # 禁止多地登录
#  is-share: true         # 共享Cookie
#  token-style: simple-uuid      # token生成策略
#  is-log: true
#  isReadCookie: false    # 是否尝试从 cookie 里读取 Token，此值为 false 后，StpUtil.login(id) 登录时也不会再往前端注入Cookie

mybatis-plus:
  # 全局配置
  global-config:
    db-config:
      id-type: auto # 主键ID自增策略
      logic-delete-field: isdeleted  # 字段名
      logic-not-delete-value: 0   # 未删除时的值（0）
      logic-delete-value: 1     # 删除时的值（当前时间）
      table-underline: true # 表名下划线转换
      capital-mode: false # 数据库大写转换

  # 配置Mapper扫描路径
  mapper-locations: classpath*:/mapper/**/*.xml

  # 类型别名包扫描路径
  type-aliases-package: com.yy.wechat.model.entity

  # 配置项
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 日志实现
    map-underscore-to-camel-case: true # 下划线转驼峰
    cache-enabled: true # 开启二级缓存
    default-fetch-size: 100 # 获取记录条数限制
    default-statement-timeout: 30 # 超时时间(秒)
    call-setters-on-nulls: true # 结果集中空值也调用setter

# 微信小程序配置
wx:
  appid: wx2f54b69827ab705f # 小程序AppID
  secret: a045c85f8c0bb4da3a5e4b8521484e53 # 小程序AppSecret
  token-expire-days:  30 # 小程序Token过期时间(天)
  cart-expire-days:  30 # 购物车过期时间(天)

logging:
  level:
    io.lettuce.core: DEBUG  # 打印Redis命令和响应
    org.springframework.data.redis.core: DEBUG